### ISSUE TITLE
Language Pack Isn't Working

### ISSUE THREAD

**Issue by kmgdevelopment** [EllisLab/EE-Language-Spanish#2]
I installed this language pack as per [the instructions in the EE docs](http://ellislab.com/expressionengine/user-guide/general/languages.html), but when I go to _My Account > Localization Settings_, select "Spanish", and click "Update", all of the control panel text is still in English.

I also have the French language pack installed and that's working fine.

**Comment by kevinsmith** [comment]
Uh oh, that's not good. I'll check it out shortly.

**Comment by kmgdevelopment** [comment]
Updating the file names (see pull request) helped a little, but basically all of the control panel navigation and publish page don't have any Spanish equivalents.

**Comment by kevinsmith** [comment]
Wow, that's so odd. The filenames are still EE 1-style filenames. Thanks for taking the lead on getting these updated. Let's continue over on the pull request...
